# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstSprintUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_heading = QtWidgets.QLabel(self.centralwidget)
        self.label_heading.setGeometry(QtCore.QRect(100, 10, 631, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_heading.setFont(font)
        self.label_heading.setWordWrap(True)
        self.label_heading.setObjectName("label_heading")
        self.button_importLog = QtWidgets.QPushButton(self.centralwidget)
        self.button_importLog.setGeometry(QtCore.QRect(40, 200, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_importLog.setFont(font)
        self.button_importLog.setObjectName("button_importLog")
        self.label_importLog = QtWidgets.QLabel(self.centralwidget)
        self.label_importLog.setGeometry(QtCore.QRect(40, 140, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_importLog.setFont(font)
        self.label_importLog.setObjectName("label_importLog")
        self.list_importedLog = QtWidgets.QListWidget(self.centralwidget)
        self.list_importedLog.setGeometry(QtCore.QRect(40, 320, 281, 201))
        self.list_importedLog.setObjectName("list_importedLog")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 280, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_showSummary = QtWidgets.QLabel(self.centralwidget)
        self.label_showSummary.setGeometry(QtCore.QRect(390, 200, 371, 231))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_showSummary.setFont(font)
        self.label_showSummary.setAutoFillBackground(True)
        self.label_showSummary.setText("")
        self.label_showSummary.setObjectName("label_showSummary")
        self.button_showLogSummary = QtWidgets.QPushButton(self.centralwidget)
        self.button_showLogSummary.setGeometry(QtCore.QRect(500, 470, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_showLogSummary.setFont(font)
        self.button_showLogSummary.setObjectName("button_showLogSummary")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_heading.setText(_translate("MainWindow", "Desktop Application Framework"))
        self.button_importLog.setText(_translate("MainWindow", "Import from PC"))
        self.label_importLog.setText(_translate("MainWindow", "Import an event log to get started"))
        self.label_3.setText(_translate("MainWindow", "Imported Log"))
        self.button_showLogSummary.setText(_translate("MainWindow", "Show Log Summary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
